version: '3.8'

services:
  python-app:
    image: python:3.8-slim
    container_name: python_container
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install torch torchvision opencv-python && tail -f /dev/null"
    tty: true
